# Настройка постоянного хранилища
persistence:
  enabled: true
  size: 5Gi
  # storageClassName: "standard" # Укажите StorageClass, если требуется

# Установка пароля администратора
adminPassword: "Password123!"

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30007



# Настройка автоматического импорта дашбордов из ConfigMaps (sidecar)
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard # Метка для ConfigMaps с дашбордами
  datasources:
    enabled: true
    label: grafana_datasource # Метка для ConfigMaps с источниками данных